server:
  port: 8081

spring: 
  application:
     name : course-service
     
  zipkin:
    enabled: true


      
  config:
    import: optional:configserver:http://localhost:8086
    

    
    
# enables Spring Boot Actuator end points
management:
  endpoints:
    web:
      exposure:
        include: "*"        
     

      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka